### ISSUE TITLE
Building on Mac

### ISSUE THREAD

**Issue by sibo7851** [aergoio/aergolite#1]
## Expected Behavior
Build source from Mac terminal using instructions from readme

## Current Behavior
apt-get doesn't exist on Mac
also:
libuv % ./autogen.sh
./autogen.sh: line 28: automake: command not found

## Possible Solution
Not sure what the Mac specific commands would be

## Steps to Reproduce

1. Copy given instructions into Mac terminal

## Context (Environment)
* **Version**: commit 588 (version not shown)
* **Platform**: Mac OS 10.15.6

**Comment by kroggen** [comment]
Indeed.

Instead of `sudo apt-get` use `brew` to install the required tools.

You must install Homebrew before.

Then run:

```
brew install git gcc make automake libtool libreadline-dev
```

I don't know if the packages names are the same. Probably gcc and git are already installed. Please inform if it works.

**Comment by sibo7851** [comment]
Yeah I tried with brew as well and didn't have any luck, brew is really restrictive on newer version of Mac.

**Comment by kroggen** [comment]
Well, this is not a AergoLite problem, but a general one. You can figure out how to install the required tools that are listed above. Once they are installed the compilation may work. If not, please inform.

**Comment by tutiplain** [comment]
While this may not be a problem directly related to Aergolite, there is a problem in the README which I think should be addressed. The README instructions specify that the same commands to install will work on both Linux and Mac, while this is not the case.
